"""downgrading

Revision ID: 60d0a022e279
Revises: 63d4f1ffb5ff
Create Date: 2025-09-22 00:32:32.421921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d0a022e279'
down_revision = '63d4f1ffb5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media_script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('news_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('article_script')
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.VARCHAR(length=500), nullable=True))

    op.create_table('article_script',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('news_item_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('social_media_script')
    # ### end Alembic commands ###
